### ISSUE TITLE
Lobby Scene Development

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#10]
A functioning lobby scene will be created in the Unity.

It must contain:

Voice chat feature:
- [ ] Users can communicate with each other through VR microphones and headsets.

Play button to start the game:
- [ ] A button will be implemented to start the game.
- [ ] Connection between users will be established to enter the first minigame.

Players can interact with objects or other players:

- [ ] In the lobby players can interact with the objects.
- [ ] Players can interact with each other physically.
- [ ] Players can see each other's movements and emotes.

ETA: 2 to 3 weeks

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli.
