### ISSUE TITLE
Login Scene Development

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#13]
Login scene will be the first scene of our game. After each user start the game they will see this and be able to customize settings of the game, choose their character and its outfit. Also VRKeys library should be imported in order to write and use keyboard.

First page in this scene must contain:
- [x] Settings page icon
- [x] Button to navigate character selection and customization
- [x] Text field for customizing user name, etc.
- [x] Button for choosing server to join rooms
- [x] Button for joining private/public rooms 

Settings page will mainly include game, audio, video and controller settings which provide user to change volume, resolution, mic, etc.

Character customization page will help user to choose their character between predefined  assets. The user should be able to choose body, outfits, etc. that belongs to their character. Every time they enter the game, they must see the previous characters they played or set. 

A player can both join random, or private/public room. This page should contain creating room choice, joining public or private room choices. If the player choose to join public room all the empty rooms in selected server must be listed. Else if they should create a room with password and the generated unique room id or they should join a private room entering room id and password. 

This issue can be divide into sub-issues.

ETA: 2-3 weeks

**Comment by cagdasgerede** [comment]
Tüm taskların içerikleri ve beklentiler tanımlanmalı. Ne zaman DONE yapılmış sayılacak tariflenmeli. Görev tanımı açık olmalı. ETA belirtilmeli. Gerekirse mock ekran görüntüleri eklenmeli.
