### ISSUE TITLE
Minigame - FPS game

### ISSUE THREAD

**Issue by Lihem** [TeamWombat2023/Bil496-Bitirme-Projesi#47]
An FPS game that is played with VR controllers.

Sample VR FPS game:
![desktop-wallpaper-superhot-dev-continuing-to-experiment-in-vr-new-game-skips-support-superhot-mind-control-delete](https://user-images.githubusercontent.com/75074894/218327165-db8cf80b-ef49-49fa-bb6b-539ee59316f4.jpg)

FPS controls should have these features:

- [x] A single-handed gun to shoot
- [x] Player movements are done by left hand controller
- [x] Gun is controlled by right hand controller
- [x] Shooting function will be done by trigger button in right hand

FPS game should have these set of rules:

- [x] If a player is shot, He/She will respawn in 5 seconds
- [x] Fresh-spawned players will be immortal for 3 seconds
- [x] Fresh-spawned players will be not able to attack other players during the immortal time
- [x] Game will be in free for all mod. That means there will be no teams
- [x] Players will spawn with guns.
- [x] Every player will start the game with 100 health.
- [x] Taking damage reduces 25 health. Player dies in 4 shoot.
- [x] If a player shoots the last bullet to an an enemy player, He/She will gain 1 point and the enemy player will instantly die.
- [x] At the end of the game player with the most points will win the game and 2nd and 3rd player will follow the same rule
- [x] Players will have an unlimited amount of ammo but shooting will have a reasonable delay

Playground design:

- [x] Playground will have bullet-proof blocks that players can hide behind.
- [x] Playground will be big enough to ensure that players can shoot from a fair distance
- [x] Playground will be closed around by walls and there will be no infinite gap that players can fall
- [x] There will be a spawn point in the middle of the playground that players will spawn at the start of the game and when they die
- [x] Players cannot interact with objects such as walls, but can hide behind them.

ETA: end of 4th sprint
