### ISSUE TITLE
Minigame - Crawl and Jump

### ISSUE THREAD

**Issue by kaanefekeles** [TeamWombat2023/Bil496-Bitirme-Projesi#48]
A simple minigame in which competing players will crawl and jump to avoid incoming obstacles. Main features and logic must be implemented. Visual effects and other polish will be added later.
Reference image:
![jump and duck](https://user-images.githubusercontent.com/73278269/218327580-0f43344e-e576-45d0-b005-97e0ca151899.PNG)

Basic functionality:
- [x] Players should be able to crawl and jump.
- [x] Player movements should be precisely tracked for collisions.
- [x] There should be a variety of obstacles and powerups.
- [x] The game should be programmed such that it provides sufficient randomness and competitiveness while being not too hard.
- [x] The players should be able to see each other.
- [x] The last remaining player should be declared winner and awarded with the most points.
- [x] After enough failures a player should fail (fall into a lava pit maybe)

Playground design:
- [x] The players should start side by side. Every time a player collides with and obstacle the player should be dragged back.
- [x] There should be a fail line(lava pit in the picture).
- [x] Players should have animations for crawling and jumping.

ETA: end of 4th sprint
