### ISSUE TITLE
Minigame - Labyrinth Game

### ISSUE THREAD

**Issue by okg21** [TeamWombat2023/Bil496-Bitirme-Projesi#49]
A labyrinth mini-game will be designed. The game is not expected to completely finish for the second sprint. Main features must work. Visual effects, sound effects and multiplayer aspects will be added later. There two possible ways for scoring. Either the maze will have an exit, and we will score based on the ranking or the labyrinth will be a closed chamber and players will be scored on collectible points.

Game should have this set of features:
- [ ] Players should be able to see and interact with each other(e.g. punching each other for a stun)
- [ ] There should be special weapons and power-ups around the labyrinth
- [ ] There should be collectible points inside the labyrinth
- [ ] The labyrinth should change during the game(e.g. moving walls, booby traps) 
- [ ] There should be parkour elements around the labyrinth(e.g. moving bridges, booby traps)

Reference:
![image](https://user-images.githubusercontent.com/24496613/218326767-24c74cb0-93b3-493d-b5f0-fa2bd3573a82.png)
![image](https://user-images.githubusercontent.com/24496613/218326785-c7577035-d3ad-4316-ac6a-787553e4b1eb.png)

ETA: end of 4th sprint
