### ISSUE TITLE
Minigame - Fruit Ninja

### ISSUE THREAD

**Issue by SelinMergen** [TeamWombat2023/Bil496-Bitirme-Projesi#57]
This mini game is a simplified version of the popular name called "Fruit Ninja". The objective of the original game is to slice fruits thrown up in the air by swiping the finger across the screen, while avoiding bombs. 

![Image](https://user-images.githubusercontent.com/72672134/218327984-f044dc64-c1af-43e2-931a-27d93b36f825.png)

But since this is not a mobile game where you can use your finger to slice fruits, we will be using VR controllers to cut objects using a sword made of a fruit like below:

![](https://user-images.githubusercontent.com/72672134/214015211-d78dbf66-09fb-40ff-82bb-213fda6c5392.png)

Basic rules of this minigame can be listed as:

1. Object of the Game: The objective of the game is to slice as many fruits as possible while avoiding bombs. The player with the highest score at the end of the game wins.
2. Gameplay: Fruits will be thrown up into the air and players must slice them by swinging their swords. If a player slices a bomb, they will lose points. 
3. Scoring: Players will receive points for each fruit they slice. Different fruits may have different point values.
4. Time Limit: The game has a time limit, after which the player with the highest score wins.
5. Power-Ups: The game may include power-ups that temporarily increase a player's score or give them an advantage in the game. For example, a power-up may slow down the speed of the fruits or increase the size of the slicing area.

Under this issue,

- [x] Asset Creation: Blender will be used to create 3D models of the fruits, bombs, and any other game assets.
- [x] Game World Creation: Unity will be used to create a game world, including a background and a slicing area.
- [x] Game Logic Implementation: Necessary codes will be written in C# to implement the game logic, including the slicing mechanism, collision detection, scoring system, and power-up mechanics.

tasks will be completed.

ETA: End of the 2nd Sprint
