### ISSUE TITLE
Minigame - Plane Game

### ISSUE THREAD

**Issue by MErenB** [TeamWombat2023/Bil496-Bitirme-Projesi#69]
A mini-game about flying planes will be developed. In the game, players will have to operate their airplanes for reaching the finish line as fast as possible. Players can pick up various empowerment in the race field. Such as empowerment to increase their speed or a flare gun to create a foggy area to distract their opponents. The following image demonstrates how the game will work.

![image](https://user-images.githubusercontent.com/78208804/218399641-455e59d2-1115-442b-82df-f2a05c084497.png)
Image: A gameplay screenshot from the VR plane flying game WW1 Fighters. In our game, players will be racing in a race field and they will pick up and use power-ups. They will use one hand for controlling the plane and they use the power-ups with their other hand. For instance, there will be a smoke bomb power-up in the game to distract other players, and it will be used like in the image: by throwing the bomb into the open air.

The rules of the game can be summarised as follows:
1. Players are racing to reach the finish line faster.
2. They can pick up various items along the way in order to increase their speed or distract other players.

The required features for the game are:

**Flying:**
- [x] Flying the airplane will be implemented.
- [x] Flying aid will be implemented to make flying slightly easier.

**Power-ups:**
- [ ] Various power-ups will be implemented.
- [x] Interaction and usage of the power-ups will be implemented.

**Design:**
- [x] A race field will be designed.
- [x] An airplane will be designed in Blender.

ETA: end of 4th sprint
