### ISSUE TITLE
Multiplayer Manager

### ISSUE THREAD

**Issue by Lihem** [TeamWombat2023/Bil496-Bitirme-Projesi#77]
Network Manager scripts for player and object interactions in real-time for minigames and for the lobby scene.

- [x] In the current project, any multiplayer features have not been included. In order to manage the multiplayer features in a game, all the movements and object location changes must be synchronized for all players.
- [x] An avatar prefab should be imported to the project for checking the movements of a player. 
- [x] Also to fulfill this task voice chat implementation must be completed. 

This issue basically be divided into 2 parts which are:

1. Player synchronization
2. Object synchronization
3. Voice Chat Implementation

ETA: 1 week
